### ISSUE TITLE
Estimated age doesn't make sense as, as time passes this changes

### ISSUE THREAD

**Issue by rcrichton** [openhie/cares-covid-ig#2]
https://github.com/openhie/cares-covid-ig/blob/36521e0e0f13772cab03acb94bf964d8a777a458/input/fsh/profiles.fsh#L115

`birthDate` is allowed to have missing values so I think we can capture and estimated date by just providing a year for example - https://hl7.org/fhir/patient-definitions.html#Patient.birthDate

**Comment by mariusnaude** [comment]
this has been communicated, will be removed today
